/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./popup.html", "./js/**/*.js"],
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "primary-container": "#1b1b1b",
        "tertiary-container": "#171c1f",
        "secondary-fixed-dim": "#a6cbeb",
        "on-surface": "#1b1c1c",
        "primary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#001e30",
        "background": "#fbf9f8",
        "on-primary-fixed-variant": "#474747",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c2c7cb",
        "secondary-fixed": "#cbe6ff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#303031",
        "surface-container-low": "#f5f3f3",
        "inverse-on-surface": "#f2f0f0",
        "surface-tint": "#5e5e5e",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "surface": "#fbf9f8",
        "tertiary": "#000000",
        "surface-dim": "#dbdad9",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        "on-surface-variant": "#4c4546",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c6c6c6",
        "surface-variant": "#e4e2e2",
        "secondary-container": "#cbe6ff",
        "on-error-container": "#93000a",
        "outline": "#7e7576",
        "on-background": "#1b1c1c",
        "surface-container-high": "#e9e8e7",
        "surface-container": "#efeded",
        "on-tertiary-fixed-variant": "#42484b",
        "surface-container-highest": "#e4e2e2",
        "secondary": "#3d627e",
        "tertiary-fixed": "#dee3e7",
        "on-tertiary-fixed": "#171c1f",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#244a65",
        "outline-variant": "#cfc4c5",
        "surface-bright": "#fbf9f8",
        "on-tertiary-container": "#7f8588",
        "on-secondary-container": "#3c617d",
        "gallagher-blue": "#a6cbeb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "margin-desktop": "48px",
        "section-margin": "20px",
        "touch-target": "32px",
        "inline-gap": "8px",
        "stack-gap": "12px",
        "container-padding": "16px"
      }
    },
  },
  plugins: [],
};
